apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  WORDPRESS_DB_HOST: mariadb-svc
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
data:
  WORDPRESS_DB_PASSWORD: Z3VpbGhlcm1l
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6-php8.1
          resources:
            limits:
              memory: "1024Mi"
              cpu: "2"
          envFrom:
            - configMapRef:
                name: wordpress-config
            - secretRef:
                name: wordpress-secret
          ports:
            - containerPort: 80
              hostPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-media-data
      volumes:
        - name: wordpress-media-data
          persistentVolumeClaim:
            claimName: wordpress-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  labels:
    name: wordpress-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wordpress.k8s.guilherme.foo
      secretName: default-ssl-certificate
  rules:
    - host: wordpress.k8s.guilherme.foo
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: wordpress-svc
                port:
                  number: 80
