apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  database-name: guilherme
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
data:
  database-user: Z3VpbGhlcm1l
  database-password: Z3VpbGhlcm1l # Base64 encoded password
---

