apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  database-name: guilherme
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
data:
  database-user: Z3VpbGhlcm1l
  database-password: Z3VpbGhlcm1l # Base64 encoded password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    app: postgres-db
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      name: postgres-db
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: database-name
                  name: database-config
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: database-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: database-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres-db
  ports:
    - targetPort: 5432
      port: 5432
